stages:
  - createCmlLab
  - prepUbuntuVm
  - addDevicesNso

image: jcomer3943/ubuntu-cml:latest

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  VALUT_TOKEN: hvs.PmfWNJASEo5ZUFlD7423IJPu
  VAULT_ADDR: http://172.0.1.10:8200

createCmlLab:
  stage: createCmlLab
  script:
    - python3 cmlLabBuilder.py --topo cmlTopo/topoBase-v2.yaml

prepUbuntuVm:
  stage: prepUbuntuVm
  script:
    - ansible-playbook -i creds/ubuntu-inv nso/ubuntuDocker.yml -u cisco
    - sleep 120
  only:
    - master

addDevicesNso:
  stage: addDevicesNso
  script:
    - ansible-playbook -i localhost nso/nsoAddDevices.yml
  only:
    - master