stages:
  - createCmlLab
  - prepUbuntuVm
  - addDevicesNso
  - ndfcCreateFabric

image: jcomer3943/ubuntu:flask

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  VAULT_TOKEN: hvs.PmfWNJASEo5ZUFlD7423IJPu
  VAULT_ADDR: http://172.0.1.10:8200

createCmlLab:
  stage: createCmlLab
  script:
    - python3 cmlLabBuilder.py --topo cmlTopo/topoBase-v2.yaml

prepUbuntuVm:
  stage: prepUbuntuVm
  script:
    - ansible-playbook -i creds/ubuntu-inv nso/ubuntuDocker.yml -u cisco
    - sleep 300
  only:
    - master

addDevicesNso:
  stage: addDevicesNso
  script:
    - ansible-playbook -i localhost nso/nsoAddDevices.yml
  only:
    - master

ndfcCreateFabric:
  stage: ndfcCreateFabric
  script:
    - python3 ndfc/ndfcVxlan.py --fabric_type Easy_Fabric --fabric cml-nxos-vxlan --seedfile vars/master/nso/nsoDevices2.csv --port_defs vars/master/vxlan/port-defs.csv
  only:
    - master